group: stable
os: linux
sudo: required
language: c

addons:
  apt:
    sources:
    - sourceline: 'ppa:wireshark-dev/stable'
    packages:
    - libglib2.0-dev
    - libwireshark-dev

install:
    - mkdir build && cd build
    - cmake ..
    - make
    - make install

script:
    - ls -l ~/.config/wireshark/plugins/ | grep libbpep.so
